version: '2'
services:
  mariadb-local:
    image: 'mariadb:latest'
    container_name: 'mariadb-local'
    ports:
      - '3306:3306'
    volumes:
      - '../mariadb-local:/var/lib/mysql'
    environment:
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
  mariadb-replicated:
    image: 'mariadb:latest'
    container_name: 'mariadb-replicated'
    ports:
      - '3316:3306'
    volumes:
      - '../mariadb-replicated:/var/lib/mysql'
    environment:
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
  mariadb-erasure:
    image: 'mariadb:latest'
    container_name: 'mariadb-erasure'
    ports:
      - '3326:3306'
    volumes:
      - '../mariadb-erasure:/var/lib/mysql'
    environment:
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
